//! Cross-language conformance: the Rust `aslc` codecs must produce byte-for-byte identical frames to
//! the shipped Android codecs. The reference bytes live in `testdata/aslc_golden.hex`, GENERATED by
//! the Android `AslcGoldenVectorGeneratorTest` (Android = source of truth). If Android's wire format
//! ever changes, regenerate the file and this test localizes the divergence to the exact vector.

use std::collections::HashMap;

use aslc::capabilities::PcmCapabilities;
use aslc::format::PcmFormat;
use aslc::frame::{
    encode_frame, MSG_CAPABILITIES, MSG_CONFIGURE, MSG_CONFIGURE_ACK, MSG_ERROR, MSG_HELLO,
    PROTOCOL_VERSION,
};
use aslc::payload::{
    capabilities_payload, configure_ack_payload, configure_payload, error_payload, hello_payload,
    pcm_data_frame,
};

fn hex_decode(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn load_golden() -> HashMap<String, Vec<u8>> {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/testdata/aslc_golden.hex");
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("missing golden file {path}: {e} (run the Android generator)"));
    let mut map = HashMap::new();
    for line in text.lines().map(str::trim).filter(|l| !l.is_empty()) {
        let (name, hex) = line.split_once('|').expect("line format NAME|hex");
        map.insert(name.to_string(), hex_decode(hex));
    }
    map
}

#[test]
fn rust_frames_match_android_golden_bytes() {
    let g = load_golden();

    let cases: [(&str, Vec<u8>); 6] = [
        (
            "HELLO",
            encode_frame(
                MSG_HELLO,
                &hello_payload(PROTOCOL_VERSION, true, "Android"),
                0,
            ),
        ),
        (
            "CAPABILITIES",
            encode_frame(
                MSG_CAPABILITIES,
                &capabilities_payload(&PcmCapabilities::full_matrix()),
                1,
            ),
        ),
        (
            "CONFIGURE",
            encode_frame(
                MSG_CONFIGURE,
                &configure_payload(PcmFormat::new(96000, 24, 2)),
                2,
            ),
        ),
        (
            "CONFIGURE_ACK",
            encode_frame(
                MSG_CONFIGURE_ACK,
                &configure_ack_payload(PcmFormat::new(96000, 24, 2), 16384),
                3,
            ),
        ),
        (
            "ERROR",
            encode_frame(
                MSG_ERROR,
                &error_payload(
                    aslc::frame::ERR_FORMAT_UNSUPPORTED,
                    MSG_CONFIGURE,
                    "device cannot render 32-bit",
                ),
                4,
            ),
        ),
        (
            "PCM_DATA",
            pcm_data_frame(5, &(0..30u8).collect::<Vec<u8>>(), 5),
        ),
    ];

    for (name, mine) in cases {
        let golden = g
            .get(name)
            .unwrap_or_else(|| panic!("golden vector {name} missing"));
        assert_eq!(
            mine,
            *golden,
            "{name}: Rust bytes diverge from Android golden\n rust:   {}\n android:{}",
            mine.iter().map(|b| format!("{b:02x}")).collect::<String>(),
            golden
                .iter()
                .map(|b| format!("{b:02x}"))
                .collect::<String>(),
        );
    }
}

#[test]
fn rust_round_trips_the_golden_control_payloads() {
    // Beyond producing identical bytes, confirm the Rust parsers read Android's exact payloads back.
    use aslc::frame::HEADER_SIZE;
    use aslc::payload::{
        parse_capabilities, parse_configure, parse_configure_ack, parse_error, parse_hello,
        pcm_frame_count,
    };

    let g = load_golden();

    let hello = &g["HELLO"];
    let h = parse_hello(&hello[HEADER_SIZE..]).unwrap();
    assert_eq!(
        (h.protocol_version, h.is_device, h.role_tag.as_str()),
        (1, true, "Android")
    );

    let caps = &g["CAPABILITIES"];
    let c = parse_capabilities(&caps[HEADER_SIZE..]).unwrap();
    assert_eq!(c, PcmCapabilities::full_matrix());

    let cfg = &g["CONFIGURE"];
    assert_eq!(
        parse_configure(&cfg[HEADER_SIZE..]),
        Some(PcmFormat::new(96000, 24, 2))
    );

    let ack = &g["CONFIGURE_ACK"];
    assert_eq!(
        parse_configure_ack(&ack[HEADER_SIZE..]),
        Some(PcmFormat::new(96000, 24, 2))
    );

    let err = &g["ERROR"];
    let e = parse_error(&err[HEADER_SIZE..]).unwrap();
    assert_eq!(e.error_code, aslc::frame::ERR_FORMAT_UNSUPPORTED);
    assert_eq!(e.message, "device cannot render 32-bit");

    let pcm = &g["PCM_DATA"];
    assert_eq!(pcm_frame_count(&pcm[HEADER_SIZE..]), 5);
}
